### DISCUSSION TITLE
能否加入全局自定义背景呢 可以用API的

### DISCUSSION THREAD

**Discussion by Kirietoan** [the1812/Bilibili-Evolved#1298] [功能建议 / Ideas]
能否加入全局自定义背景呢 可以用API的

**Comment by the1812** [comment]
可以试下 Stylus 插件, 强行把 body 的背景图换掉
```css
body { background-image: url('xxx.jpg') }
```

**Reply by Kirietoan** [reply]
> 可以试下 Stylus 插件, 强行把 body 的背景图换掉
> 
> ```css
> body { background-image: url('xxx.jpg') }
> ```

不太行诶 只有在加载前会显示一下背景 加载脚本后无了

**Reply by the1812** [reply]
开了夜间? 加个 `!important` 应该能行
```css
body {
  background-image: url('https://i0.hdslb.com/bfs/album/0e6264d78b0fc4b071d401e601b3dca0b51ea1a4.png') !important;
  background-size: contain;
}
```
