### DISCUSSION TITLE
希望简化直播间的系统提示

### DISCUSSION THREAD

**Discussion by u2shana** [the1812/Bilibili-Evolved#2192] [功能建议 / Ideas]
![QQ截图20210823122446](https://user-images.githubusercontent.com/14146754/130390740-bd4b3e96-b8d1-4525-b64f-1fecb1652fbc.jpg)

每次进直播间都会有，虽然是善意的提醒，不过这么长的一大段确实有点影响了

能用上这脚本的人都怎么都会有明辨是非的能力吧

**Comment by the1812** [comment]
可以, CSS 我先放出来了
```css
.chat-item.convention-msg { display: none !important }
```
