### DISCUSSION TITLE
去除 正在看 人数 减少焦虑

### DISCUSSION THREAD

**Discussion by shigasia** [the1812/Bilibili-Evolved#2841] [功能建议 / Ideas]
去除 正在看 人数 减少焦虑

原因 : 某些视频需要静心学习, 正在看人数比较干扰,增加焦虑

**Comment by woshizhizhang** [comment]
为什么这个会引起焦虑呢？

**Comment by ShuiHuo** [comment]
安装个 [Stylus](https://github.com/openstyles/stylus)，访问 B站 后在扩展中点击 `新建样式给 bilibili.com` 填入

```CSS
.bpx-player-video-info, .bilibili-player-video-info {
	display: none;
}
```
