### DISCUSSION TITLE
如何隐藏触碰弹幕时显示的点赞、复制、举报浮层？

### DISCUSSION THREAD

**Discussion by ZzzzzzzSkyward** [the1812/Bilibili-Evolved#2917] [提问 / Q&A] [answered]
如题，理论上只需要一条css规则
```css
.bpx-player-dialog-wrap{
display:none!important;
}
```
但我应该如何添加？
