### DISCUSSION TITLE
厚着脸皮提一个功能，弹幕描边相关

### DISCUSSION THREAD

**Discussion by oscarwty** [the1812/Bilibili-Evolved#3486] [功能建议 / Ideas]
我现在的情况是，弹幕只有微软雅黑+加粗能勉强够字重，在这样的情况下
我透明度开的是80%（再高就实在挡视频了，而且我开到100%，重墨的范围也还是很快衰减到透明）
默认的三种描边都太浅了，也就重墨稍微好点（但对比度还是有点弱，应该是描边范围不够大），选描边是真的细得不行
而且动起来和暂停截图是两回事，动起来就真的感觉浅
不知道作者方不方便考虑一下这方面的改进，或者有什么现成的工具，谢谢……
win10 ltsc 2021
firefox 102

**Comment by the1812** [comment]
可以装个 Stylus, 自己改一下弹幕的字重, 100~950 都行, 我自己用的 600
```css
.b-danmaku,
.bilibili-danmaku {
  font-weight: 600 !important;
}
```
![image](https://user-images.githubusercontent.com/26504152/177895116-943f23e2-7a60-4420-80a8-993ffeb9c21f.png)

**Reply by oscarwty** [reply]
谢谢，请问阴影着色怎么改

**Reply by the1812** [reply]
用 [text-shadow](https://developer.mozilla.org/en-US/docs/Web/CSS/text-shadow)
```css
.b-danmaku,
.bilibili-danmaku {
  font-weight: 600 !important;
  text-shadow: black 0 0 8px !important;
}
```
