### DISCUSSION TITLE
请问极简首页的网页背景色和tag可以跟v1一样是偏灰的么，全白有点费眼睛.....

### DISCUSSION THREAD

**Discussion by Gentlema** [the1812/Bilibili-Evolved#3711] [提问 / Q&A] [answered]
<img width="960" alt="Snipaste_2022-09-29_08-08-49" src="https://user-images.githubusercontent.com/40130916/192909997-367871de-ad66-46a9-9a90-8f329d7e3d8f.png">
<img width="960" alt="Snipaste_2022-09-29_08-09-01" src="https://user-images.githubusercontent.com/40130916/192910005-456aded9-8ca7-4960-99a5-1b0bed3da131.png">
上面v2下面v1，还是说可以自己调的么，找不到入口...看久了眼睛会累，我的屏幕缩放不支持我列宽调成2列

**Comment by mammuto** [comment]
请问怎么在首页只显示动态，我想要这个，找了很久找不到，如果可以请教教我，感激不尽

**Reply by the1812** [reply]
安装 `极简首页`

**Reply by mammuto** [reply]
谢谢，不过我在”在线“里面搜不到极简首页

**Reply by mammuto** [reply]
嗷嗷！找到啦

**Comment by the1812** [comment, marked as answer]
[homeRedesign.grayBackground.zip](https://github.com/the1812/Bilibili-Evolved/files/9695448/homeRedesign.grayBackground.zip)

可以装一下这个样式 (复制链接粘贴安装)

![image](https://user-images.githubusercontent.com/26504152/193522378-c4ffeb7b-770f-49a4-b5f9-c0fe89b86817.png)

**Reply by Gentlema** [reply]
谢谢大哥，我还想问下极简首页那个视频标签的填充色是哪个代码呀，我自己尝试改了一下但没有生效。。。

**Reply by the1812** [reply]
```css
.home-redesign-base {
  --home-base-color: #f4f4f4 !important;
}
.video-card .topics .topic {
  background-color: 这里
}
```
