### DISCUSSION TITLE
首页恢复彩色

### DISCUSSION THREAD

**Discussion by zzhzero** [the1812/Bilibili-Evolved#3856] [功能建议 / Ideas]
修改html标签上的样式应该就可以
`element.style{filter:none;}`

**Comment by Ethkuil** [comment]
应该没必要，更新版本也要时间，那时候哀悼应该已经结束了。

而为将来其他可能的变化做准备似乎也意义不大？

**Comment by Geeyun-JY3** [comment]
有各网站通杀的脚本吧

**Comment by the1812** [comment]
建议去 Stylus 里加, 其他网站也能生效
```css
html, body { filter: none !important }
```
