### DISCUSSION TITLE
希望可以替换b站的字体为默认字体

### DISCUSSION THREAD

**Discussion by machine-doll** [the1812/Bilibili-Evolved#4052] [功能建议 / Ideas]
b站目前用的是鸿蒙字体，感觉在非整数缩放下不怎么清晰，至少没有浏览器默认的字体清晰
希望可以提供一个选项，覆盖掉b站的字体设定，使用浏览器默认字体

**Comment by the1812** [comment]
可以用 Stylus 改下, 附一份我目前用的, 字体可以改成自己喜欢的:
```css
html
{
    --general-font-family: 'Sarasa UI SC', 'Segoe UI Emoji', 'Segoe UI Symbol', ControlIcons, sans-serif;
    --monospace-font-family: 'Iosevka Curly Slab', 'Sarasa Mono SC', 'Segoe UI Emoji', 'Segoe UI Symbol', monospace;
}
*:not(i):not([class*='icon']):not(b):not([class~='fa']):not([class*='Icon']):not([class*='docon'])
{
    font-family: var(--general-font-family) !important;
}
kbd:not(i):not([class*='icon']):not(b):not([class~='fa']):not([class*='Icon']):not([class~='docon']), 
pre:not(i):not([class*='icon']):not(b):not([class~='fa']):not([class*='Icon']):not([class~='docon']), 
code:not(i):not([class*='icon']):not(b):not([class~='fa']):not([class*='Icon']):not([class~='docon']),
pre span:not(i):not([class*='icon']):not(b):not([class~='fa']):not([class*='Icon']):not([class~='docon']),
code span:not(i):not([class*='icon']):not(b):not([class~='fa']):not([class*='Icon']):not([class~='docon'])
{
    font-family: var(--monospace-font-family) !important;
}
```
