### DISCUSSION TITLE
更新了变色弹幕，禁用特殊弹幕样式无效

### DISCUSSION THREAD

**Discussion by Nyte-BK201** [the1812/Bilibili-Evolved#4227] [功能建议 / Ideas]
希望跟进一下，去掉炫彩弹幕样式

**Comment by Moenupa** [comment]
我看了一眼DOM然后简单ban了一下

```css
.bili-dm-vip { background: none !important; }
```

能用但是我看style还改了其他的东西 可能有一些样式的小问题

原DOM是这样的（我开了 dark reader 所以会有一些奇怪的注入，忽略就好）

```html
<div class="bpx-player-primary-area">
   <div class="bpx-player-video-area">
      <div class="bpx-player-row-dm-wrap bili-paused">
         <div aria-live="polite" role="comment" class="bili-dm bili-center bili-show" style="--opacity: 0.3; --fontSize: 25px; --fontFamily: 'Noto Sans CJK SC DemiLight', Arial, Helvetica, sans-serif; --fontWeight: normal; --color: #ffffff; --offset: 0px; --translateX: -1186px; --duration: 2.2835249999999974s; --top: 40px; --darkreader-text--color: #f0ebe2; --darkreader-border--color: #323535;">
            <div style="background: url(&quot;http://i0.hdslb.com/bfs/dm/b4f545290caf5a90bd9a96c8d4edefd09bca79bc.png&quot;) text; text-shadow: none; -webkit-text-stroke: 4px transparent; --darkreader-inline-bgcolor: initial;" class="bili-dm-vip" data-darkreader-inline-bgcolor="">
            主摄没有OIS防抖，荣耀老传统了
            </div>
         </div>
      </div>
   </div>
</div>
```

**Reply by Moenupa** [reply]
用:has我感觉没必要 直接ban background就行
他这个style是直接写进DOM的 我去看了遍css发现好像没改其他的
所以要么把这个URL拦截掉 要么对class的css做手脚 要么直接DOM上改也行

**Reply by Moenupa** [reply]
应该很好修的 麻烦大佬们了

**Reply by rcyggdra** [reply]
加个字体描边，不然弹幕看起来发白。


```css
.bili-dm-vip {text-shadow: 1px 0 1px #000000,0 1px 1px #000000,0 -1px 1px #000000,-1px 0 1px #000000 !important; }
```
