### DISCUSSION TITLE
建议去除某些直播间的马赛克功能

### DISCUSSION THREAD

**Discussion by CuewarsTaner** [the1812/Bilibili-Evolved#4736] [功能建议 / Ideas]
作者你好，现在B站直播的某些分区，例如Apex分区的部分主播，因为游戏画面可能会有敏感ID或字符，网页端直播间的代码里多了一个DIV元素，实现了马赛克遮挡。

请问是否可以加入一个功能？实现自动移除这个马赛克。

DIV的id="web-player-module-area-mask-panel"

直播间示例：https://live.bilibili.com/30407385
详情马赛克请看下图：
![image](https://github.com/the1812/Bilibili-Evolved/assets/46869194/4555a26a-09d8-4367-9dca-2ff8828417e7)

**Comment by festoney8** [comment]
讨论过，B 站对这个元素有检测机制（display 和 visibility）。https://github.com/the1812/Bilibili-Evolved/discussions/4634

可以暂时自行用 stylus 给直播页增加样式解决

```css
.web-player-module-area-mask {
    backdrop-filter: none !important;
}
```
