### DISCUSSION TITLE
[feat] 显示完整视频标题

### DISCUSSION THREAD

**Discussion by razilong** [the1812/Bilibili-Evolved#4780] [功能建议 / Ideas]
### 对应功能

视频播放页面当标题过长时另起一行以显示完整标题。

我注意到 #761 ，个人同样希望能有一个【显示完整视频标题】的新组件。因为如果没有，需要手动把鼠标精准移动到长标题右边的符号上才能完整阅读完这个视频的标题----这是非常麻烦的。

### 问题描述

​

### 脚本版本

v2.8.12-36-gf53902062

### 脚本管理器及版本

Violentmonkey v2.19

### 浏览器及版本

Chrome 122

### 播放器版本

v4.8.5

### 播放策略

默认

### 错误信息

```Shell
​
```

### 致遇到了相同问题准备回复的人

**太长不看**：
1、遇到了相同的问题：**请用左下角的 reaction 点赞**
2、实时关注该 Issue 的后续进展：**请用 Issue 页上的 Subscribe 功能**（在 PC 端按钮通常位于页面右侧）。
**_请您回复前务必确认您有在本 Issue 之外补充了其它相关信息（比如 Log）再行回复以免对他人造成不必要的困扰_**
<details>
  <summary>完整版</summary>
    由于每个 Issue 甚至整个项目都是可以订阅通知的, 对于已经有人汇报过的 Bug, 如果您也遇到了并且没有其他信息要补充, 可以直接在左下点个赞表示 +1, 不要再去新增评论。想关注后续的可以用 Subscribe，Subscribe 之后该 Issue 如果有变动都可以收到通知，如果不想被回复打扰可以使用更加进阶的 Customize 功能，勾选 "Closed" & "Reopened"。Closed 通常代表该 Issue 已被解决，极少数情况下的 Reopened 代表该 Issue 的问题重新出现。如果您新增了无意义评论，因为 Issue 这个 bug tracker 与<a href="https://www.zhihu.com/question/23757640">邮件列表</a>类似，订阅某个 Issue 的用户会在每次这个 Issue 有新的动态时收到一封新的提醒邮件。也就是说，在 Issue 中的一个不能提供新的信息的评论，相当于给所有订阅这个 Issue 的用户发了一封垃圾邮件（spam）。尤其项目的维护者也是订阅者中的一员，太多垃圾邮件会对维护者带来很多不必要的困扰。发送垃圾邮件在开源社区通常是不那么受欢迎的行为。
</details>

**Comment by the1812** [comment]
> 因为如果没有，需要手动把鼠标精准移动到长标题右边的符号上才能完整阅读完这个视频的标题----这是非常麻烦的。

用不着这样, 直接放在标题任意一个字上停留一会就能看到完整标题了

**Comment by festoney8** [comment]
用 [stylus](https://chromewebstore.google.com/detail/clngdbkpkpeebahjckkjfobafhncgmne) 新增一个样式就行，网址匹配按图片里的写

```css
.video-info-container:has(.show-more) {
    height: fit-content !important;
    margin-bottom: 12px;
}
.video-info-container .video-info-title-inner-overflow .video-title {
    margin-right: unset !important;
    text-wrap: wrap !important;
}
.video-info-container .video-info-title-inner .video-title .video-title-href {
    text-wrap: wrap !important;
}
.video-info-container .show-more {
    display: none !important;
}
```

![image](https://github.com/the1812/Bilibili-Evolved/assets/36254268/b64054d3-e771-4dd1-9903-398c5f66a09f)
