### DISCUSSION TITLE
直播间网页全屏自适应

### DISCUSSION THREAD

**Discussion by DecCapri** [the1812/Bilibili-Evolved#4895] [功能建议 / Ideas]
直播间弹幕栏下加了醒目留言和点赞按钮，导致当直播间网页全屏后侧栏显示不全，希望能把这两个按钮去了
![PixPin_2024-09-05_15-13-20](https://github.com/user-attachments/assets/a40db61b-33b6-47e6-8498-47b6ec0f811c)

**Comment by Geeyun-JY3** [comment]
你图没传上来……

**Reply by DecCapri** [reply]
重新上传了

**Comment by the1812** [comment]
应该可以集成到简化直播间里

顺便吐槽下这圆角写的真烂
![Snipaste_2024-09-05_22-45-02](https://github.com/user-attachments/assets/0fd947cb-8a02-46c1-aee7-00792631b924)

**Reply by DecCapri** [reply]
期待，B站网页很多地方的ui都是一坨

**Reply by the1812** [reply]
看了下其实是开着 `直播间网页全屏自适应` 太挤了才会这样, 把字去掉就行了
![Snipaste_2024-09-08_21-16-36](https://github.com/user-attachments/assets/d5b79003-1dfb-4a01-a6f1-63395198632b)

**Reply by u2shana** [reply]
> 看了下其实是开着 `直播间网页全屏自适应` 太挤了才会这样, 把字去掉就行了 ![Snipaste_2024-09-08_21-16-36](https://private-user-images.githubusercontent.com/26504152/365440549-d5b79003-1dfb-4a01-a6f1-63395198632b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4NDU4MTYsIm5iZiI6MTcyNTg0NTUxNiwicGF0aCI6Ii8yNjUwNDE1Mi8zNjU0NDA1NDktZDViNzkwMDMtMWRmYi00YTAxLWE2ZjEtNjMzOTUxOTg2MzJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA5VDAxMzE1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwZjIyNWU5Zjg1YWYwMmZjMDg2YjBhZDA2ZDFhY2FkYzk5MzViN2Q0ZjgyNjhhOTkzYzA2NDM3MWU5MzliMjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rwX0pgikau6NPEhpx5nx5C_9A5uteE1TH7OqXjErTIg)

这两个按钮有大又丑，还会挡住一些其他脚本添加的按钮。有办法永久隐藏文字么，现在只是宽度小到一定程度才隐藏

**Reply by DecCapri** [reply]
> 看了下其实是开着 `直播间网页全屏自适应` 太挤了才会这样, 把字去掉就行了 ![Snipaste_2024-09-08_21-16-36](https://private-user-images.githubusercontent.com/26504152/365440549-d5b79003-1dfb-4a01-a6f1-63395198632b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4NzE3MDEsIm5iZiI6MTcyNTg3MTQwMSwicGF0aCI6Ii8yNjUwNDE1Mi8zNjU0NDA1NDktZDViNzkwMDMtMWRmYi00YTAxLWE2ZjEtNjMzOTUxOTg2MzJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA5VDA4NDMyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFmOTI0MmYwOGQ3MzU0N2ZiNzMyMDM2MzE4ZTkzYzNkMWI4MmNkYjdhZWVjM2MzMTZjNDBhNDNiMTBiY2Y2M2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GtxgIznCtjM8C9UAMzQmcBA18OADmpNvcxK2VudKncI)

怎么把字去掉啊

**Reply by DecCapri** [reply]
更新预览版后看到了，挺好的

**Reply by the1812** [reply]
> 这两个按钮有大又丑，还会挡住一些其他脚本添加的按钮。有办法永久隐藏文字么，现在只是宽度小到一定程度才隐藏

可以把那段样式加到 Stylus 里常驻生效
```css
.control-panel-icon-row-new .icon-left-part-new .super-chat,
.control-panel-icon-row-new .icon-left-part-new .like-btn {
  width: 32px;
}
.control-panel-icon-row-new .icon-left-part-new .super-chat-icon,
.control-panel-icon-row-new .icon-left-part-new .like-btn-icon {
  margin-right: 0 !important;
}
.control-panel-icon-row-new .icon-left-part-new .super-chat-text,
.control-panel-icon-row-new .icon-left-part-new .like-btn-text {
  display: none !important;
}
```
