### DISCUSSION TITLE
为旧版动态页面提供评论区图片查看，或提供新版动态页面的微调使其字体渲染正常

### DISCUSSION THREAD

**Discussion by Starseeker-H** [the1812/Bilibili-Evolved#4954] [功能建议 / Ideas]
不选择“体验新版”的话动态的评论区里的图片是无法看到的，但新版动态页面存在一些小问题，比如整体元素略大（原本分的比较开的up头像挤到一块略不舒服），字体渲染糊

（比较奇怪的是，动态详情界面是默认新版，字体渲染却没有问题）

另，希望可以提供对动态页面的背景替换 ，空着也是空着不如放点想看的（

**Comment by the1812** [comment]
旧版动态看 b 站这样子估计后面要废弃了, 就不再加功能了
新版字体渲染糊是什么样子的?

背景替换 Stylus 建个样式就行:
```css
#app .bg {
  background-image: url(图片地址) !important;
}
```
