### ISSUE TITLE
关于视频播放的高亮点赞弹幕

### ISSUE THREAD

**Issue by LIERTTTTTT** [the1812/Bilibili-Evolved#1228]
如题，请问作者能否推出能够屏蔽视频中高亮的点赞弹幕的功能，金色的太扎眼了很影响观看，谢谢作者！（例：https://www.bilibili.com/bangumi/play/ss29310  第五话08：50开始的金色弹幕【瞬间下岗】）

**Comment by Geeyun-JY3** [comment]
今天发现高亮点赞弹幕换了个样式，干扰性小了些
![image](https://user-images.githubusercontent.com/49396421/104115196-8db27b80-5347-11eb-9c68-5247d3863b9d.png)

**Comment by the1812** [comment]
草 我代码都写好了 咋又换了

**Comment by LIERTTTTTT** [comment]
> 草 我代码都写好了 咋又换了

草，火 阿B 火.jpg

**Comment by Geeyun-JY3** [comment]
不知道是不是还在灰度（

**Comment by Geeyun-JY3** [comment]
应该是尘埃落定了：https://www.bilibili.com/read/cv9277652

**Comment by Geeyun-JY3** [comment]
居然又改了一版……：
![image](https://user-images.githubusercontent.com/49396421/119791216-33394680-bf07-11eb-9dab-bb56057f2f26.png)

**Comment by the1812** [comment]
看起来应该没改太多, 我之前写的 CSS 应该可以用
```css
.b-danmaku-high .b-danmaku-high-icon {
  display: none !important;
}
.b-danmaku-high .b-danmaku-high-text {
  margin: 0 !important;
  text-shadow: inherit;
}
.b-danmaku-high {
  display: line-height !important;
  padding: 0 !important;
  line-height: 1.125 !important;
}
```
