### ISSUE TITLE
强制固定顶栏与侧栏功能导致侧边栏与动态内容重合

### ISSUE THREAD

**Issue by ssxwcz** [the1812/Bilibili-Evolved#1888]
**关于哪一项功能**
强制固定顶栏与侧栏

**问题描述**

打开个人动态页面，开启**强制固定顶栏与侧栏功能**后，侧边栏就会与动态内容重合。

**脚本版本**

预览离线版1031.78

**浏览器版本**

chrome 91.0.4472.77

**错误信息**

**附加截图**
![image](https://user-images.githubusercontent.com/43665491/119843214-eae74c00-bf39-11eb-9d72-808723b6923b.png)
![image](https://user-images.githubusercontent.com/43665491/119843194-e4f16b00-bf39-11eb-9548-83ae5831563e.png)

**Comment by NTDLX** [comment]
同款问题

**Comment by JimMoen** [comment]
相同问题，但似乎只存在于高分屏上
我有两块显示器，
1920x1080屏幕上未出现此问题
2560x1440屏幕上出现了这个问题
猜测原因是某个地方的比例使用了以1080p屏幕未基准的绝对值而不是相对值

**Comment by NTDLX** [comment]
> 相同问题，但似乎只存在于高分屏上
> 我有两块显示器，
> 1920x1080屏幕上未出现此问题
> 2560x1440屏幕上出现了这个问题
> 猜测原因是某个地方的比例使用了以1080p屏幕未基准的绝对值而不是相对值

有可能，未在1080P屏幕上测试，本人使用的屏幕分辨率为3440*1440

**Comment by the1812** [comment]
是的, b站新增了 1080P 以上屏幕的代码
```css
@media screen and (min-width: 1921px) {
    .home-content[data-v-9197f874] {
        width: 60.42vw !important;
    }
    .home-content .left-panel[data-v-9197f874] {
        width: 12.71vw !important;
    }
    .home-content .center-panel[data-v-9197f874] {
        width: 32.92vw !important;
    }
    .home-content .right-panel[data-v-9197f874] {
        width: 13.96vw !important;
    }
}
@media screen and (min-width: 2497px) {
    .home-content[data-v-9197f874] {
        width: 1508px !important;
    }
    .home-content .left-panel[data-v-9197f874] {
        width: 317px !important;
    }
    .home-content .center-panel[data-v-9197f874] {
        width: 822px !important;
    }
    .home-content .right-panel[data-v-9197f874] {
        width: 348px !important;
    }
}
```
