### ISSUE TITLE
番剧网页全屏下播放器底部缺少底色

### ISSUE THREAD

**Issue by MapleRecall** [the1812/Bilibili-Evolved#233]
给播放器加个背景色就好了
```css
#bilibiliPlayer {
    box-shadow: 0 4px 8px 0 #0004;
    background: #222;
}
```
**附加截图**
![image](https://user-images.githubusercontent.com/18360825/68786191-503a5b80-067a-11ea-8be9-27f78dcbb7fb.png)
