### ISSUE TITLE
脚本中使用了 CSS 类 "icon"，被 B 站 CSS 影响

### ISSUE THREAD

**Issue by timongh** [the1812/Bilibili-Evolved#3371]
### 对应功能

/

### 问题描述

脚本中使用了 CSS 类 "icon"，该类被 B 站文件 <https://s1.hdslb.com/bfs/static/jinkela/space/css/space.8.bc20968cc588a9712629030e4fd86e8a508ebabb.css> 影响。该文件中有以下内容：

```css
 #browser-version-tip #close-browser-tip, .icon {
  display: inline-block;
  background-image: url(//s1.hdslb.com/bfs/static/jinkela/space/assets/icons.png);
}
```

这段内容使脚本显示了不该显示的图案（在任意用户的个人主页打开脚本设置）：

![图片](https://user-images.githubusercontent.com/46739861/170837616-8b035908-5f8b-4aa8-ae08-e650889f3f89.png)

### 脚本版本

/

### 浏览器版本

/

### 播放器版本

/

### 播放策略

默认

### 错误信息

```shell
/
```
