### ISSUE TITLE
关于您的字体设置问题

### ISSUE THREAD

**Issue by XMMM0917** [the1812/Bilibili-Evolved#370]
您好！在Greasy Fork上看到了您的截图，感觉您的字体设置非常好看！
想知道如何实现同您一样的字体效果？
万分感谢！

**Comment by XMMM0917** [comment]
@the1812

**Comment by the1812** [comment]
那个字体是`方正准圆`, 不过由于不支持日文字符我已经弃用很久了, 因为网络问题一直无法更改Greasy Fork上的信息
替换到网页上是使用了 Stylus 插件, 不过代码是我胡乱写的所以没有公开发布, 需要的话我在这里导出了一份给您:
```css
@-moz-document regexp("^((?!(twitter\\.com|kotlincn\\.net|kotlinlang\\.org|fonts\\.google\\.com|console\\.aliyun\\.com|leetcode-cn\\.com)).)*$") {
html
{
    --general-font-family: '更纱黑体 UI SC', 'Segoe UI Emoji', 'Segoe UI Symbol', 'FZZhunYuan-M02', 'Gen Jyuu Gothic Regular', 'Microsoft YaHei UI', ControlIcons, sans-serif;
    --monospace-font-family: 'Iosevka SS05 Medium', 'Sarasa Mono SC', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Microsoft YaHei Mono', monospace;
}
*:not(i):not([class*='icon']):not(b):not([class~='fa']):not([class*='Icon']):not([class*='docon'])
{
    font-family: var(--general-font-family) !important;
}
kbd:not(i):not([class*='icon']):not(b):not([class~='fa']):not([class*='Icon']):not([class~='docon']), 
pre:not(i):not([class*='icon']):not(b):not([class~='fa']):not([class*='Icon']):not([class~='docon']), 
code:not(i):not([class*='icon']):not(b):not([class~='fa']):not([class*='Icon']):not([class~='docon']),
pre span:not(i):not([class*='icon']):not(b):not([class~='fa']):not([class*='Icon']):not([class~='docon']),
code span:not(i):not([class*='icon']):not(b):not([class~='fa']):not([class*='Icon']):not([class~='docon'])
{
    font-family: var(--monospace-font-family) !important;
}
}

@-moz-document domain("github.com") {
table.highlight span:not(i):not([class*='icon']):not(b):not([class~='fa']):not([class*='Icon']):not([class~='docon']),
.blob-code span:not(i):not([class*='icon']):not(b):not([class~='fa']):not([class*='Icon']):not([class~='docon']),
table.highlight td:not(i):not([class*='icon']):not(b):not([class~='fa']):not([class*='Icon']):not([class~='docon'])
{
    font-family: var(--monospace-font-family) !important;
}
}

@-moz-document domain("alst.net") {
.header-search:not(i):not([class*='icon']):not([class~='fa']):not([class*='Icon']):not([class~='docon']),
.header-search-x:not(i):not([class*='icon']):not([class~='fa']):not([class*='Icon']):not([class~='docon'])
{
    font-family: "FontAwesome" !important;
}
}

@-moz-document domain("i.hdu.edu.cn") {
[class^="in_"]:not(i):not([class*='icon']):not([class~='fa']):not([class*='Icon']):not([class~='docon']),
[class*=" in_"]:not(i):not([class*='icon']):not([class~='fa']):not([class*='Icon']):not([class~='docon'])
{
    font-family: 'new_icon' !important;
}
[class^="ii_"]:not(i):not([class*='icon']):not([class~='fa']):not([class*='Icon']):not([class~='docon']),
[class*=" ii_"]:not(i):not([class*='icon']):not([class~='fa']):not([class*='Icon']):not([class~='docon'])
{
    font-family: 'icomoon' !important;
}
.fa:not([class^="ii_"]):not([class*=" ii_"]):not([class^="in_"]):not([class*=" in_"]):not(i):not([class*='icon'])
{
    font-family: "FontAwesome" !important
}
}

@-moz-document domain("tmall.com") {
.j_AddCart:not(i):not([class*='icon']):not(b):not([class~='fa']):not([class*='Icon'])
{
    font-family: chaoshi-list-iconfont !important;
}
}

@-moz-document domain("www.nowcoder.com") {
.caret:not(i):not([class*='icon']):not([class~='fa']):not([class*='Icon']):not([class~='docon'])
{
    font-family: "FontAwesome" !important;
}
}
```
在 Stylus 里选择`Write New Style`, 在`Mozilla Format`下面选择`Import`, 粘贴那些代码并选择`Overwrite style`.
在代码里`--general-font-family: '更纱黑体 UI SC' ...`那行可以改成您喜欢的字体, `--monospace-font-family: `那行是用于代码类的字体.
另外, 那封邮件应该也是您写的吧, 我就不再回复了.
