### ISSUE TITLE
直播间开启屏幕适配导致设置面板显示不全

### ISSUE THREAD

**Issue by Despair21** [the1812/Bilibili-Evolved#4275]
### 对应功能

设置面板

### 问题描述

在直播间开启实验室-屏幕适配后脚本的设置面板显示不全，也不能用滚轮滑动
显示器分辨率为2560x1440

### 脚本版本

v2.7.2-53-g81aba0ace

### 脚本管理器及版本

Tampermonkey v4.19.0

### 浏览器及版本

Microsoft Edge 版本 114.0.1823.58 (正式版本) (64 位)

### 播放器版本

Bilibili HTML5 Live Player 3.6.127

### 播放策略

默认

### 错误信息

```Shell
无
```

### 附加截图

未开启屏幕适配
![image](https://github.com/the1812/Bilibili-Evolved/assets/70837010/e8db5e83-77f1-46c3-a8fa-080f3bcb3e34)

开启屏幕适配
![image](https://github.com/the1812/Bilibili-Evolved/assets/70837010/3be4314f-05f1-4c68-b762-257b485b4574)

**Comment by the1812** [comment]
开启屏幕适配后多了个 zoom, 这让我咋适配...
```css
@media screen and (min-width: 2058px)
html[lab-style*=adaptive] {
    zoom: calc(4/3);
}
```
