### ISSUE TITLE
新增 AI视频总结 目前夜间模式未适配

### ISSUE THREAD

**Issue by Sabiary** [the1812/Bilibili-Evolved#4482]
### 对应功能

夜间模式

### 问题描述

新增 AI视频总结 目前夜间模式未适配

### 脚本版本

v2.8.5-preview-103-g35578ac47

### 脚本管理器及版本

暴力猴v2.15.0

### 浏览器及版本

edge 117.0.2045.60

### 播放器版本

不相关

### 播放策略

AV1

### 错误信息

```Shell
不相关
```

### 附加截图

[
![微信截图_20231010181748](https://github.com/the1812/Bilibili-Evolved/assets/34003386/adc27823-e039-494c-9d8b-1278a8004d5c)
](url)

### 致遇到了相同问题准备回复的人

**太长不看**：
1、遇到了相同的问题：**请用左下角的 reaction 点赞**
2、实时关注该 Issue 的后续进展：**请用 Issue 页上的 Subscribe 功能**（在 PC 端按钮通常位于页面右侧）。
**_请您回复前务必确认您有在本 Issue 之外补充了其它相关信息（比如 Log）再行回复以免对他人造成不必要的困扰_**
<details>
  <summary>完整版</summary>
    由于每个 Issue 甚至整个项目都是可以订阅通知的, 对于已经有人汇报过的 Bug, 如果您也遇到了并且没有其他信息要补充, 可以直接在左下点个赞表示 +1, 不要再去新增评论。想关注后续的可以用 Subscribe，Subscribe 之后该 Issue 如果有变动都可以收到通知，如果不想被回复打扰可以使用更加进阶的 Customize 功能，勾选 "Closed" & "Reopened"。Closed 通常代表该 Issue 已被解决，极少数情况下的 Reopened 代表该 Issue 的问题重新出现。如果您新增了无意义评论，因为 Issue 这个 bug tracker 与<a href="https://www.zhihu.com/question/23757640">邮件列表</a>类似，订阅某个 Issue 的用户会在每次这个 Issue 有新的动态时收到一封新的提醒邮件。也就是说，在 Issue 中的一个不能提供新的信息的评论，相当于给所有订阅这个 Issue 的用户发了一封垃圾邮件（spam）。尤其项目的维护者也是订阅者中的一员，太多垃圾邮件会对维护者带来很多不必要的困扰。发送垃圾邮件在开源社区通常是不那么受欢迎的行为。
</details>

**Comment by shirok1** [comment]
使用下面的 CSS 可以让总结里的字体按照官方的颜色进行

<img width="446" alt="image" src="https://github.com/the1812/Bilibili-Evolved/assets/12044683/eccad2c2-8671-492d-8b44-01610c31ec31">

```css
.ai-summary-popup .section-title {
    color: var(--theme-color) !important;
}
.ai-summary-popup .content {
    color: inherit !important;
}
```

**Comment by PeterYRZ** [comment]
怎么使用这样的CSS呢？是有哪个插件可以自定义CSS吗？还是我需要在浏览器中更改？

谢谢解答。

> 使用下面的 CSS 可以让总结里的字体按照官方的颜色进行
> 
> <img alt="image" width="446" src="https://user-images.githubusercontent.com/12044683/282807480-eccad2c2-8671-492d-8b44-01610c31ec31.png">
> ```css
> .ai-summary-popup .section-title {
>     color: var(--theme-color) !important;
> }
> .ai-summary-popup .content {
>     color: inherit !important;
> }
> ```

**Comment by PeterYRZ** [comment]
[https://greasyfork.org/zh-CN/scripts/479919-bilibili%E7%BD%91%E7%AB%99ai%E6%80%BB%E7%BB%93%E5%A4%9C%E9%97%B4%E6%A8%A1%E5%BC%8F%E6%A0%B7%E5%BC%8F%E4%BF%AE%E5%A4%8D](url)
@Sabiary 我根据 @shirok1 的Comment编写了一个脚本，用以临时修正“AI视频总结”的显示效果，你可以试试，看是否在你的设备上生效。
这个脚本在我的设备上的效果如下：
![image](https://github.com/the1812/Bilibili-Evolved/assets/50796002/e62800e4-b5eb-4f24-9d4e-2fee57bee100)
我的脚本写的不是很好，颜色和背景颜色应该使用索引，但我目前就这样使用了，“夜间模式”组件的作者应该会修复的吧

**Comment by shirok1** [comment]
@PeterYRZ 我用的是 [Stylus](https://add0n.com/stylus.html) 插件，专门用来附加样式的插件，不需要脚本。

**Comment by ZhangTianrong** [comment]
暂时我是写了个这样的样式，感觉还行
```css
.ai-summary-popup {
    border: 0px;
    box-shadow: 0 0 30px rgba(34,34,34,.10196);
    background: #333333;
}

.ai-summary-popup-body-outline .section:hover {
    background-color: #444444;
}

.ai-summary-popup-body-abstracts {
    color: #eeeeee;
}

span.ai-summary-popup-tips-text {
    color: #eeeeee !important;
}

.ai-summary-popup-header {
    background: none;
}

.resizable-component {
    background: #333333;
}

.ai-summary-popup-body-outline .section .section-title:before {
    background: #eeeeee;
}

.video-ai-assistant.disabled:hover::after {
    display: block;
    background: #333333;
    border: 0px;
}
```
![image](https://github.com/the1812/Bilibili-Evolved/assets/20651728/6cf121d9-1feb-4a7a-840a-5bcce92893a2)

![image](https://github.com/the1812/Bilibili-Evolved/assets/20651728/5c394a67-708c-497b-beb0-3d59ce4269c0)

**Comment by PeterYRZ** [comment]
@ZhangTianrong 你的样式写得很好！我还是喜欢在AI总结悬浮窗中的节标题上保留原网站的样式，即节标题是主题色显示的。同时，我希望鼠标移动到每一个可点击的标题上时，标题的颜色如标题开头的时间点一样会响应变色。这些行为按我的写法是可以达成的，我也参考了你的样式，更新了我的脚本。
https://greasyfork.org/zh-CN/scripts/479919-bilibili%E7%BD%91%E7%AB%99ai%E6%80%BB%E7%BB%93%E5%A4%9C%E9%97%B4%E6%A8%A1%E5%BC%8F%E6%A0%B7%E5%BC%8F%E4%BF%AE%E5%A4%8D
Stylus确实很好用，谢谢 @shirok1 的推荐

**Comment by Den-ze** [comment]
@PeterYRZ 老师，可否更新下您的脚本！QAQ

**Comment by tiamed** [comment]
已更新

**Comment by ZhangTianrong** [comment]
呃，其实是 B 站改了一堆名字，导致之前的样式无效了，现在可以用这个临时修改的
```css
/* Better dark theme for the AI Summary  */
.ai-summary-popup, div[data-video-assistant-subject] {
    border: 0px;
    box-shadow: 0 0 30px rgba(34,34,34,.10196);
    background: #333333;
}

.ai-summary-popup-body-outline .section:hover, div[data-video-assistant-subject-tabs], div[class^='_SearchBar_']:not([class*=' _Shrinked_']), div[class^='_SearchBtn_']:hover, div[class^='_CloseBtn_']:hover{
    background-color: #444444 !important;
}

div[class^='_Part_']:hover {
    background: #242628 !important;
}

div[class^='_Part_']:hover div[class^='_Content_'] {
    color: #00A0D8 !important;
}

div[class^='_Part_'] div[class^='_TimeText_'] {
    background: #444444 !important;
    color: white !important;
}

div[class^='_Part_']:hover div[class^='_TimeText_'] {
    background: #242628 !important;
    color: #00A0D8 !important;
}

div[class^='_Feedback_'] div[class^='_Btn_']:hover {
    background: #444444 !important;
    color: #00A0D8 !important;
}

.ai-summary-popup-body-abstracts {
    color: #eeeeee;
}

span.ai-summary-popup-tips-text {
    color: #eeeeee !important;
}

.ai-summary-popup-header {
    background: none;
}

.resizable-component {
    background: #333333;
}

.ai-summary-popup-body-outline .section .section-title:before {
    background: #eeeeee;
}

.video-ai-assistant.disabled:hover::after {
    display: block;
    background: #333333;
    border: 0px;
}

.ai-summary-popup-header-right .ai-summary-popup-close:hover, .ai-summary-popup-header-right .ai-summary-popup-dislike:hover, .ai-summary-popup-header-right .ai-summary-popup-like:hover {
    color: #eeeeee;
}

.ai-summary-popup-header-left .ai-summary-popup-tips-main .tips-icon:hover {
    color: #eeeeee;
}
```
