### ISSUE TITLE
夜间模式与哔哩哔哩助手版聊功能有冲突

### ISSUE THREAD

**Issue by Cansll** [the1812/Bilibili-Evolved#632]
**关于哪一项功能**
夜间模式

**问题描述**

直播间启动夜间模式，哔哩哔哩助手打开版聊功能后，在网页全屏右侧会有一块遮挡屏幕的灰色区域。

**脚本版本**

预览版1.10.28

**浏览器版本**

Chrome 83

**错误信息**

**附加截图**
![image](https://user-images.githubusercontent.com/11648014/84843971-e5bc2480-b07b-11ea-98be-79aaad340c6c.png)

**Comment by Coulomb-G** [comment]
那就把版聊模式关了吧,去设置面板开启「直播全屏弹幕栏」看看

**Comment by Cansll** [comment]
> 那就把版聊模式关了吧,去设置面板开启「直播全屏弹幕栏」看看

我看见那个功能了，但是我想要左边那个弹幕栏...所以还是继续开版聊了...

**Comment by Cansll** [comment]
我加了个样式，算是解决问题了...
```css
div#aside-area-vm {
    background: rgba(0,0,0,0)!important;
}
```
